export type ServiceData = {
  slug: string;
  title: string;
  headline: string;
  description: string;
  heroImage: string;
  whyTitle: string;
  whyDescription: string;
  whyPoints: string[];
  whyQuote: string;
  processTitle: string;
  processSteps: { title: string; description: string }[];
  benefitsTitle: string;
  benefits: { title: string; description: string }[];
  benefitsQuote?: string;
  whoTitle: string;
  whoPoints: string[];
  faqs: { question: string; answer: string }[];
  finalTitle: string;
  finalDescription: string;
};

export const SERVICES_DATA: ServiceData[] = [
  {
    slug: "maintenance-support",
    title: "Maintenance & Support",
    headline: "We stay with you after launch to keep your product stable, secure, and ready for new features.",
    description: "Your product doesn't end at launch. It needs continuous care. We keep everything running smoothly so you can focus on growth.",
    heroImage: "/images/service-maintenance.jpg",
    whyTitle: "Why maintenance & support matters",
    whyDescription: "Even the best systems need regular updates and improvements. Without maintenance, you risk:",
    whyPoints: [
      "Slow performance",
      "Security vulnerabilities",
      "Outdated features",
      "Broken integrations",
      "User frustration",
      "Costly emergency fixes",
    ],
    whyQuote: "We help you stay ahead of these issues so your product remains fast, secure, and reliable.",
    processTitle: "Our maintenance process",
    processSteps: [
      { title: "Health check", description: "We review your system, performance, security, and bugs." },
      { title: "Monthly updates", description: "Regular improvements to keep everything smooth." },
      { title: "Bug resolutions", description: "Fast fixes before they affect users." },
      { title: "Feature iterations & enhancements", description: "We help your product evolve with time." },
    ],
    benefitsTitle: "Benefits of our maintenance & support",
    benefits: [
      { title: "Peace of mind", description: "We monitor your product so you don't have to." },
      { title: "Higher stability", description: "Your system stays fast and reliable." },
      { title: "Stronger security", description: "Regular checks protect you from risks." },
      { title: "Consistent improvements", description: "Your product grows with new features." },
      { title: "Fewer emergencies", description: "Most issues are fixed before they become problems." },
    ],
    benefitsQuote: "Launching your product is step one. Keeping it strong is where we come in.",
    whoTitle: "Who needs maintenance?",
    whoPoints: [
      "Startups with active users",
      "Products that need continuous updates",
      "Businesses adding new features regularly",
      "Companies without an in-house tech team",
      "Platforms with complex integrations",
    ],
    faqs: [
      { question: "How quickly do you resolve issues?", answer: "Typically within 24 to 48 hours." },
      { question: "Do you support systems built by others?", answer: "Yes, after an initial audit." },
      { question: "Will you add new features?", answer: "Yes, based on your plan." },
      { question: "Can you monitor servers too?", answer: "Absolutely." },
      { question: "Do you offer emergency support?", answer: "Yes, included in our premium plan." },
    ],
    finalTitle: "Keep your product running at its best",
    finalDescription: "A great product needs consistent care. We make sure your system stays modern, secure, and ready for growth. Let's keep your product running at its best, every single day.",
  },
  {
    slug: "ai-app-completion",
    title: "AI App Completion & Production Engineering",
    headline: "Turn your AI built prototype into a real product.",
    description: "AI tools like Lovable, Replit, v0 and Base44 make it possible to build apps fast. Appycodes helps founders transform AI generated apps into production grade systems with clean architecture, custom logic, secure infrastructure and polished user experience.",
    heroImage: "/images/service-ai.jpg",
    whyTitle: "From AI Prototype to Production Ready Product",
    whyDescription: "AI coding platforms are powerful for rapid experimentation. They can generate full stack applications from simple prompts. However production software requires more than generated code. Real products need performance optimisation, security hardening, scalable architecture and carefully designed user experience.",
    whyPoints: [
      "System architecture and clean codebase",
      "Feature completion beyond what AI builders support",
      "Design refinement and polished UX",
      "Infrastructure deployment and monitoring",
    ],
    whyQuote: "Your idea already exists. We help make it real, stable and ready to grow.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "Project Review", description: "We analyse the AI generated codebase and understand the architecture." },
      { title: "Stabilisation", description: "We refactor the code and prepare the system for reliable development." },
      { title: "Feature Completion", description: "We implement missing features and improve the user experience." },
      { title: "Production Launch", description: "We deploy the product on secure infrastructure with monitoring and support." },
    ],
    benefitsTitle: "What We Deliver",
    benefits: [
      { title: "AI Built App Engineering", description: "Codebase review, architecture improvements, refactoring AI generated logic into clean maintainable code." },
      { title: "Bespoke Product Design", description: "Design system creation, UX improvements, mobile responsive design and brand aligned UI." },
      { title: "Advanced Integrations", description: "Payment systems, CRM platforms, analytics tools, authentication providers and AI model providers." },
      { title: "Production Grade Deployment", description: "Cloud infrastructure, CI/CD pipelines, containerised environments, monitoring and security configuration." },
    ],
    benefitsQuote: "Build faster with AI. Launch strong with engineering.",
    whoTitle: "When This Service Is Perfect For You",
    whoPoints: [
      "You built a prototype using an AI builder",
      "You want to launch a real product",
      "Your AI generated code needs stability improvements",
      "You want to add custom features beyond what the builder supports",
      "You want production deployment and infrastructure",
      "You want experienced engineers to take the product forward",
    ],
    faqs: [
      { question: "Which AI builders do you work with?", answer: "We work with Lovable, Replit, v0, Base44, Bolt, Cursor generated projects and custom AI generated codebases." },
      { question: "Can you improve an app I already launched?", answer: "Yes, we can audit, stabilise and improve any existing AI built application." },
      { question: "Do you handle backend and database work?", answer: "Absolutely. Backend improvements, database restructuring, API integrations and security hardening are all included." },
      { question: "How long does it take to go from prototype to production?", answer: "Typically 4 to 12 weeks depending on the scope and complexity of the project." },
      { question: "Will my app be scalable after your work?", answer: "Yes, we build with scalability, performance and long term maintainability in mind." },
    ],
    finalTitle: "Your AI app already exists. Now let's make it production ready.",
    finalDescription: "AI tools make it easier than ever to build the first version of a product. Turning that prototype into a reliable platform still requires engineering experience. Let us help you move from AI experiment to real product.",
  },
  {
    slug: "ai-prototype-to-native-app",
    title: "AI Prototype to Native App Development",
    headline: "Turn your AI built prototype into a high performance mobile app.",
    description: "Convert your AI-built web prototype (Lovable, v0, Replit, Base44) into a production-ready native iOS + Android app. Real engineering, App Store ready.",
    heroImage: "/images/service-ai-to-native-app.jpg",
    whyTitle: "From AI Prototype to Real Mobile Product",
    whyDescription: "AI generated apps are a powerful starting point. They validate ideas, define workflows and give you a working version of your product. However mobile apps require a different level of engineering. Performance, responsiveness, offline handling, push notifications and device level integrations all need to be handled carefully. We take your existing prototype and rebuild it into a native or cross platform mobile app that works reliably at scale.",
    whyPoints: [
      "Consumer mobile apps",
      "SaaS companion apps",
      "Marketplace apps",
      "Internal business apps",
      "AI powered mobile tools",
      "Community and social apps",
      "Booking and service apps",
    ],
    whyQuote: "Your prototype becomes a real product available on app stores.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "Prototype Review", description: "We analyse your existing app and understand the product logic." },
      { title: "Mobile Architecture Planning", description: "We design how the mobile app will be structured and connected." },
      { title: "App Development", description: "We build the mobile app with clean code and strong performance." },
      { title: "Launch and Optimisation", description: "We deploy the app, monitor usage and improve performance." },
    ],
    benefitsTitle: "Native App Engineering",
    benefits: [
      { title: "iOS and Android native apps", description: "Full native development for both major platforms." },
      { title: "Cross platform apps", description: "Using React Native or Flutter for efficient multi-platform delivery." },
      { title: "Scalable backend integration", description: "Robust server infrastructure that grows with your users." },
      { title: "Secure authentication systems", description: "Industry standard security for user data protection." },
      { title: "Real time features and sync", description: "Live data, chat, tracking and synchronisation across devices." },
      { title: "Push notifications and engagement", description: "Keep users informed and engaged with smart notifications." },
      { title: "Offline support and data handling", description: "Your app works reliably even without internet connectivity." },
      { title: "Performance optimisation", description: "Smooth, fast experience across all devices and network conditions." },
      { title: "App store ready builds", description: "Complete deployment to App Store and Google Play." },
    ],
    benefitsQuote: "Your app feels natural on mobile, not like a web app inside a wrapper.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "You have built a prototype using an AI tool",
      "You want to launch a mobile app for your product",
      "Your current app is web only and needs a mobile version",
      "You want better performance and user experience on mobile",
      "You want to publish your app on app stores",
      "You want engineers to handle the full mobile build",
    ],
    faqs: [
      { question: "Which AI platforms do you work with?", answer: "We convert prototypes built using Lovable, v0, Replit, Base44, Bolt, custom AI generated codebases, and existing web apps." },
      { question: "Do you rebuild the entire app from scratch?", answer: "We take the logic and workflows from your prototype and rebuild them into a properly engineered mobile app, not a wrapper." },
      { question: "Can you carry AI features into the mobile app?", answer: "Yes. AI chat interfaces, assistants, recommendations, search, voice processing and personalised experiences are all supported." },
      { question: "Do you handle backend development too?", answer: "Yes. We connect your app with existing backends or build custom backend systems including APIs, databases and real time sync." },
      { question: "How long does it take?", answer: "Typically 6 to 14 weeks depending on the complexity of your prototype and the mobile features required." },
    ],
    finalTitle: "Build Once. Reach Users Everywhere.",
    finalDescription: "AI tools help you build the first version of your product. Mobile apps help you reach users where they spend most of their time. Appycodes bridges that gap by turning your prototype into a real mobile experience. Let's build a product your users can download and use every day.",
  },
  {
    slug: "app-store-launch",
    title: "App Store Launch",
    headline: "Launch your mobile app on the App Store and Play Store with confidence.",
    description: "Building a mobile app is only part of the journey. Getting it live on app stores requires the right setup, compliance, testing and optimisation to ensure a smooth approval and strong first impression. Appycodes helps you prepare, publish and optimise your app for both the App Store and Google Play.",
    heroImage: "/images/service-mobile.jpg",
    whyTitle: "From Build to Public Launch",
    whyDescription: "Many apps face delays during launch due to missing requirements, policy issues or improper setup. We ensure your app meets platform guidelines and is fully prepared for submission. From build configuration to store listing, we take care of everything required to move your app from development to public availability.",
    whyPoints: [
      "App Store and Play Store account setup",
      "App build preparation and configuration",
      "Submission and review process",
      "Compliance with platform guidelines",
      "Store listing creation and optimisation",
      "Version management and updates",
    ],
    whyQuote: "Your app reaches users without unnecessary delays.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "App Review", description: "We analyse your app and identify requirements for launch." },
      { title: "Preparation", description: "We prepare builds, listings and compliance elements." },
      { title: "Submission", description: "We submit your app and manage the review process." },
      { title: "Launch and Optimisation", description: "We support post launch improvements and updates." },
    ],
    benefitsTitle: "App Store Optimisation",
    benefits: [
      { title: "Title and description optimisation", description: "Clear, keyword-rich listings that improve discoverability." },
      { title: "Keyword optimisation", description: "Strategic keyword placement for better search rankings." },
      { title: "Screenshots and preview content", description: "Professional visual assets that drive downloads." },
      { title: "Technical readiness", description: "Build configuration, signing, device compatibility and performance checks." },
      { title: "Compliance and approval support", description: "Policy compliance, privacy setup, rejection handling and resubmission." },
      { title: "Analytics and tracking setup", description: "User analytics, event tracking, crash reporting and performance monitoring." },
    ],
    benefitsQuote: "A well executed launch sets the foundation for your app's success.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "You have built a mobile app and want to publish it",
      "You need help with app store submission and approval",
      "You want to optimise your app listing for better downloads",
      "You want to avoid delays and rejections",
      "You want support beyond the initial launch",
    ],
    faqs: [
      { question: "Do you handle both App Store and Play Store?", answer: "Yes. We manage the complete submission process for both Apple App Store and Google Play Store." },
      { question: "Can you help if my app was rejected?", answer: "Absolutely. We review rejection feedback, fix issues and handle resubmission." },
      { question: "Do you create the store listing content?", answer: "Yes. We optimise titles, descriptions, keywords, screenshots and all visual assets." },
      { question: "Do you support post-launch updates?", answer: "Yes. Version updates, performance monitoring and listing improvements are included." },
      { question: "How long does the launch process take?", answer: "Typically 1 to 3 weeks depending on app readiness and review timelines." },
    ],
    finalTitle: "Launch Your App the Right Way",
    finalDescription: "A well executed launch sets the foundation for your app's success. Let's get your app live on the App Store and Play Store.",
  },
  {
    slug: "tech-stack-migration",
    title: "Tech Stack Migration",
    headline: "Upgrade your technology without disrupting your business.",
    description: "Outdated systems slow down growth, limit scalability and make it harder to add new features. Appycodes helps you migrate your applications to modern, scalable technologies with minimal disruption to your operations.",
    heroImage: "/images/service-web.jpg",
    whyTitle: "Move to a Stack That Supports Growth",
    whyDescription: "Legacy systems often become difficult to maintain and expensive to scale. New features take longer to build. Performance issues become frequent. Integrations become harder to manage. A modern tech stack improves performance, flexibility and long term maintainability.",
    whyPoints: [
      "Web applications and platforms",
      "Mobile app backends",
      "Legacy CMS systems",
      "Ecommerce platforms",
      "Monolithic applications",
      "Database systems",
      "Cloud infrastructure",
    ],
    whyQuote: "Your system is rebuilt on a stronger and more scalable foundation.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "System Review", description: "We analyse your current system and identify challenges." },
      { title: "Migration Planning", description: "We define the new architecture and migration strategy." },
      { title: "Execution", description: "We migrate your system with careful implementation." },
      { title: "Testing and Launch", description: "We ensure stability and deploy the updated system." },
    ],
    benefitsTitle: "Migration Engineering",
    benefits: [
      { title: "Existing system analysis", description: "Deep review of current architecture and pain points." },
      { title: "Data migration and validation", description: "Careful transfer and verification of all data." },
      { title: "Backend and API migration", description: "Modern backend systems with clean API architecture." },
      { title: "Minimised risk and downtime", description: "Phased migration, parallel systems and rollback strategies." },
      { title: "Modern technologies", description: "Modern frontend frameworks, scalable backends, API driven and AI ready architecture." },
      { title: "Improved performance", description: "Faster load times, better responsiveness, reduced technical debt." },
    ],
    benefitsQuote: "You don't need to rebuild everything from scratch to improve your technology.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "Your current tech stack is outdated",
      "Your system is slow or hard to maintain",
      "You want to scale your product efficiently",
      "You need better performance and reliability",
      "You want to modernise your architecture",
    ],
    faqs: [
      { question: "Will my business be disrupted during migration?", answer: "No. We use phased migration with parallel systems to ensure zero downtime." },
      { question: "Can you migrate any tech stack?", answer: "Yes. We handle migrations across web apps, mobile backends, CMS, ecommerce, databases and cloud infrastructure." },
      { question: "Do you preserve existing data?", answer: "Absolutely. Data migration and validation is a core part of our process." },
      { question: "How long does a migration take?", answer: "Typically 6 to 16 weeks depending on system complexity and scope." },
      { question: "Will integrations continue to work?", answer: "Yes. All integrations are preserved or improved during the migration." },
    ],
    finalTitle: "Upgrade Without Starting Over",
    finalDescription: "A well planned migration allows you to retain what works while upgrading what doesn't. Let's migrate your system to a stronger foundation.",
  },
  {
    slug: "white-label-development",
    title: "White Label Development for Agencies",
    headline: "Expand your service capacity without expanding your internal team.",
    description: "Agencies often win more projects than their internal team can handle. Appycodes works as your white label development partner, delivering high quality engineering under your brand. Your clients see your agency. We handle the execution behind the scenes.",
    heroImage: "/images/service-consulting.jpg",
    whyTitle: "Scale Your Agency Without Hiring",
    whyDescription: "Growth creates pressure on delivery. Instead of turning down projects or stretching your team, you can extend your capacity with a reliable development partner. We integrate into your workflow and deliver projects as part of your team.",
    whyPoints: [
      "Web applications and websites",
      "Mobile apps for iOS and Android",
      "AI powered features and systems",
      "Ecommerce platforms",
      "Custom software solutions",
      "API integrations and backend systems",
      "Internal tools and dashboards",
    ],
    whyQuote: "Your agency grows without operational strain.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "Understanding Your Agency", description: "We learn your services, processes and expectations." },
      { title: "Team Alignment", description: "We align our developers with your workflow and tools." },
      { title: "Project Execution", description: "We deliver work as part of your team under your brand." },
      { title: "Ongoing Collaboration", description: "We support your agency across multiple projects as needed." },
    ],
    benefitsTitle: "How White Label Collaboration Works",
    benefits: [
      { title: "Work delivered under your brand", description: "Your clients never know about us. Everything ships under your name." },
      { title: "Flexible engagement models", description: "Project based, dedicated support, long term partnerships or overflow handling." },
      { title: "Quality and consistency", description: "Clean code, structured process, clear communication and on time delivery." },
      { title: "AI and modern capabilities", description: "We help agencies offer AI integrations, automation and advanced systems." },
      { title: "Confidential partnership", description: "Full confidentiality, no direct client outreach and secure data handling." },
      { title: "Code in your repositories", description: "All work delivered into your systems with documentation and handover support." },
    ],
    benefitsQuote: "Your reputation depends on quality. We deliver consistently.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "You need additional development capacity",
      "You want to offer more services without hiring",
      "You have overflow work during busy periods",
      "You want a reliable technical partner",
      "You want to maintain quality while scaling",
    ],
    faqs: [
      { question: "Will my clients know about you?", answer: "No. We operate completely behind the scenes under your brand." },
      { question: "Can you work with our project management tools?", answer: "Yes. We adapt to your tools, processes and communication channels." },
      { question: "What types of projects can you handle?", answer: "Web apps, mobile apps, AI features, ecommerce, custom software, APIs and internal tools." },
      { question: "Is there a minimum project size?", answer: "No. We handle projects of all sizes from small tasks to full product builds." },
      { question: "How quickly can you start?", answer: "Most engagements begin within one to two weeks." },
    ],
    finalTitle: "Your Development Partner Behind the Scenes",
    finalDescription: "Agencies grow faster when they have strong execution partners. Let's help you scale your agency with confidence.",
  },
  {
    slug: "startup-launch-support",
    title: "Startup Launch Support",
    headline: "From idea to live product with everything needed to launch and grow.",
    description: "Building a startup requires more than just development. Founders need a clear product, fast execution and a reliable setup to launch without delays. Appycodes helps you take your idea from concept to a fully functional product ready for users, customers and growth.",
    heroImage: "/images/service-ai.jpg",
    whyTitle: "Launch Faster With the Right Foundation",
    whyDescription: "Many startups lose time trying to figure out what to build, how to build it and which tools to use. We bring structure to your launch process and help you move from idea to working product quickly. Speed matters at this stage. So does building it right.",
    whyPoints: [
      "SaaS platforms",
      "AI powered products",
      "Marketplaces",
      "Mobile apps",
      "Internal tools turned into products",
      "Web platforms and dashboards",
      "Automation based products",
    ],
    whyQuote: "Your product is built with a clear focus on usability and growth.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "Idea and Planning", description: "We define your product, features and roadmap." },
      { title: "Design and Architecture", description: "We design the user experience and system architecture." },
      { title: "Build", description: "We develop the product with a focus on speed and quality." },
      { title: "Launch and Support", description: "We deploy the product and support you post launch." },
    ],
    benefitsTitle: "Complete Product Build",
    benefits: [
      { title: "Product scoping and feature definition", description: "Clear product planning before development begins." },
      { title: "UI and UX design", description: "User focused design that drives engagement and retention." },
      { title: "Frontend and backend development", description: "Full stack engineering with modern technologies." },
      { title: "AI feature integration", description: "AI assistants, automation workflows and data driven features." },
      { title: "Launch ready infrastructure", description: "Cloud hosting, security, monitoring, performance optimisation and backups." },
      { title: "Growth and tracking setup", description: "Analytics, event tracking, funnel tracking and performance monitoring." },
    ],
    benefitsQuote: "Startups move fast. Your product should too.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "You have a product idea and want to launch quickly",
      "You need a technical partner to build your startup",
      "You want a complete product without managing multiple vendors",
      "You want to include AI features in your product",
      "You want a reliable launch with proper infrastructure",
    ],
    faqs: [
      { question: "Do you help with product planning?", answer: "Yes. We help define features, roadmap and architecture before development begins." },
      { question: "Can you build both web and mobile?", answer: "Absolutely. We handle full stack web development and native or cross-platform mobile apps." },
      { question: "Do you include AI features?", answer: "Yes. AI assistants, automation workflows and data driven features are part of our offering." },
      { question: "How fast can you launch?", answer: "MVPs typically launch in 4 to 8 weeks, full products in 10 to 16 weeks." },
      { question: "Do you support after launch?", answer: "Yes. Ongoing maintenance, feature updates and growth support are available." },
    ],
    finalTitle: "Build. Launch. Grow.",
    finalDescription: "Startups move fast. Your product should too. Let's turn your idea into a live product.",
  },
  {
    slug: "api-and-integration",
    title: "API & Integration",
    headline: "Connect your systems, tools and platforms into one seamless workflow.",
    description: "Modern businesses rely on multiple tools and platforms to operate. When these systems don't communicate properly, teams waste time and data becomes inconsistent. Appycodes helps you design and implement reliable APIs and integrations that connect your entire tech ecosystem.",
    heroImage: "/images/service-web.jpg",
    whyTitle: "Build Connected Systems That Scale",
    whyDescription: "As your business grows, your systems need to exchange data efficiently. Manual workarounds and disconnected tools slow down operations and create errors. Strong API architecture allows systems to communicate in real time and scale without friction.",
    whyPoints: [
      "Payment gateways",
      "CRM platforms",
      "Ecommerce systems",
      "Analytics tools",
      "Marketing automation platforms",
      "AI services and APIs",
      "Internal business tools",
      "Third party SaaS platforms",
    ],
    whyQuote: "Your business runs faster when your systems are connected.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "System Analysis", description: "We understand your current tools and data flow." },
      { title: "Integration Design", description: "We design how systems will connect and exchange data." },
      { title: "Implementation", description: "We build APIs and integrations with clean architecture." },
      { title: "Testing and Deployment", description: "We ensure stability, security and performance." },
    ],
    benefitsTitle: "API Development and Engineering",
    benefits: [
      { title: "Custom API development", description: "REST and GraphQL APIs built for your specific needs." },
      { title: "Secure authentication and access control", description: "Industry standard security for all API communications." },
      { title: "Third party API integrations", description: "Connect with payment systems, CRMs, analytics and SaaS platforms." },
      { title: "Automation through integration", description: "Automatic data sync, trigger based workflows and cross system updates." },
      { title: "Reliable and secure systems", description: "Error handling, monitoring, rate limiting and data protection." },
      { title: "API documentation and versioning", description: "Clear documentation for maintainability and team collaboration." },
    ],
    benefitsQuote: "Disconnected tools slow down your business. Strong integrations fix that.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "You use multiple tools that need to work together",
      "You want to automate data flow across systems",
      "You need custom APIs for your product",
      "You want to integrate third party services into your app",
      "You want to reduce manual work and errors",
    ],
    faqs: [
      { question: "What types of APIs do you build?", answer: "REST APIs, GraphQL APIs, webhook based integrations and custom API systems." },
      { question: "Can you integrate with our existing tools?", answer: "Yes. We connect with payment gateways, CRMs, ecommerce systems, analytics tools and any platform with an API." },
      { question: "Do you handle API security?", answer: "Absolutely. Secure authentication, access control, error handling and monitoring are included." },
      { question: "Can you automate workflows through integrations?", answer: "Yes. We build trigger based workflows, automatic data sync and cross system automation." },
      { question: "How long does an integration project take?", answer: "Typically 2 to 8 weeks depending on the number and complexity of integrations." },
    ],
    finalTitle: "Build Systems That Work Together",
    finalDescription: "Strong integrations create a smooth flow of data and operations across your entire system. Let's build integrations that make your business run smoothly.",
  },
  {
    slug: "ai-saas-product-development",
    title: "AI SaaS Product Development",
    headline: "Build scalable AI powered SaaS products ready for real users and revenue.",
    description: "AI has opened up a new wave of software products. Appycodes helps you design and build AI SaaS products from the ground up, from architecture and core features to billing systems and deployment, with a focus on performance, scalability and monetisation.",
    heroImage: "/images/service-ai.jpg",
    whyTitle: "From Idea to AI SaaS Product",
    whyDescription: "Building a SaaS product requires more than just development. You need the right architecture, clear feature planning, user management, billing systems and a reliable backend that can handle growth. AI adds another layer where models, data and workflows need to be integrated carefully into the product experience.",
    whyPoints: [
      "AI powered tools and platforms",
      "Subscription based SaaS products",
      "Internal AI tools converted into SaaS",
      "Automation platforms",
      "Analytics and reporting tools",
      "Market specific SaaS solutions",
      "B2B and B2C platforms",
    ],
    whyQuote: "Your product is built to support real users, not just demos.",
    processTitle: "Our Approach",
    processSteps: [
      { title: "Product Planning", description: "We define the product scope, features and architecture." },
      { title: "System Design", description: "We design the SaaS architecture and AI integration." },
      { title: "Development", description: "We build the platform with clean code and scalable systems." },
      { title: "Launch and Growth", description: "We deploy the product and support ongoing improvements." },
    ],
    benefitsTitle: "Core SaaS Engineering",
    benefits: [
      { title: "Multi tenant architecture", description: "Isolated, secure environments for each customer." },
      { title: "Subscription and billing systems", description: "Plans, pricing tiers, usage based billing and payment gateway integration." },
      { title: "AI inside your SaaS product", description: "AI copilots, search, recommendations, automated workflows and content generation." },
      { title: "Admin dashboards and controls", description: "Full admin panels for user management, analytics and system controls." },
      { title: "Production grade deployment", description: "Cloud infrastructure, CI/CD, monitoring, security and scalable backends." },
      { title: "User authentication and access control", description: "Secure authentication with role based permissions." },
    ],
    benefitsQuote: "The real challenge is building a system that users trust, pay for and continue to use.",
    whoTitle: "When This Service Is Right For You",
    whoPoints: [
      "You want to build an AI SaaS product from scratch",
      "You have an idea for a subscription based platform",
      "You want to monetise an AI tool or workflow",
      "You need a scalable backend for your product",
      "You want a complete product build with engineering support",
    ],
    faqs: [
      { question: "Do you handle billing and payments?", answer: "Yes. Subscription plans, usage based billing, free trials, payment gateway integration and invoice management." },
      { question: "Can you integrate AI models into the product?", answer: "Absolutely. We integrate AI copilots, search, recommendations, content generation and automated workflows." },
      { question: "Do you build multi-tenant systems?", answer: "Yes. Multi tenant architecture with isolated, secure environments for each customer." },
      { question: "What technologies do you use?", answer: "React, Next.js, Node.js, PostgreSQL, cloud platforms, AI model APIs and third party integrations." },
      { question: "How long does it take to build an AI SaaS product?", answer: "Typically 10 to 20 weeks depending on product complexity and feature scope." },
    ],
    finalTitle: "Build a SaaS Product That Scales",
    finalDescription: "AI makes it easier to build powerful products. Let's turn your idea into a scalable platform that users trust and pay for.",
  },
];
